---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 2
  ansible_verbose: true

platforms:
  - name: ubuntu-14.04

verifier:
  name: serverspec
  sudo: true
  sudo_path: true

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/test.yml
    verifier:
      default_pattern: true
