---
sudo: required
services:
  - docker

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
#  - ANSIBLE_VERSION=2.3.0.0
#  - ANSIBLE_VERSION=2.2.0.0
#  - ANSIBLE_VERSION=2.1.0.0


cache: pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler

install:
  - bundle install
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  - ansible --version
  - docker version
  - sudo locale-gen en_GB.UTF-8
  - bundle show
  - LANG=en_GB.UTF-8 bundle exec kitchen --version
  - LANG=en_GB.UTF-8 bundle exec kitchen test -d always

after_success:
  - echo "Success"
